### ISSUE TITLE
Mod works fine but i get an error while loading

### ISSUE THREAD

**Issue by BlackwingHawkeye** [Parker8283/BowInfinityFix#6]
MC: 1.18.1
Forge: 39.1.2

09:13:44.265
game
net.minecraftforge.fml.util.ObfuscationReflectionHelper$UnableToFindFieldException: java.lang.NoSuchFieldException: INFINITY_ARROWS
	at LAYER PLUGIN/fmlcore@1.18.1-39.1.2/net.minecraftforge.fml.util.ObfuscationReflectionHelper.findField(ObfuscationReflectionHelper.java:241)
	at TRANSFORMER/infinitymending@0.1.0/me.pieking1215.infinitymending.RegistryEvents.registerTileEntities(RegistryEvents.java:28)
	at net.minecraftforge.eventbus.ASMEventHandler_114_RegistryEvents_registerTileEntities_Register.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at LAYER PLUGIN/javafmllanguage@1.18.1-39.1.2/net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at LAYER PLUGIN/fmlcore@1.18.1-39.1.2/net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)

**Comment by Parker8283** [comment]
The error comes from "Infinity Mending", which is not my mod, but a different/similar mod. Report to that mod's author(s).

**Comment by BlackwingHawkeye** [comment]
I'm sorry. My bad. 
You are absolutely right, of course.
Thank you.
