### ISSUE TITLE
Not complatible with REI mod

### ISSUE THREAD

**Issue by jdominguezs** [Parker8283/BowInfinityFix#8]
Hi! I just added your mod to my server and crashes everytime I try to fire my bow.

Here's the extract that leads me to think that it is due to REI incompatibility

```
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.parker8283.bif.BowInfinityFix.infinityFix(BowInfinityFix.java:23) ~[BowInfinityFix-1.19.x-forge-2.5.0.jar%23210!/:2.5.0] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2380!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onArrowNock(ForgeEventFactory.java:556) ~[forge-1.19.3-44.1.1-universal.jar%23259!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.item.BowItem.m_7203_(BowItem.java:110) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraft.world.item.ItemStack.m_41682_(ItemStack.java:274) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:mixin,xf:fml:forge:itemstack,re:classloading,pl:rei_plugin_compatibilities:B,xf:fml:forge:itemstack}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233716_(MultiPlayerGameMode.java:373) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:toolswap:toolswap,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233729_(MultiPlayerGameMode.java:250) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:toolswap:toolswap,pl:runtimedistcleaner:A}
	at net.minecraft.client.multiplayer.MultiPlayerGameMode.m_233721_(MultiPlayerGameMode.java:361) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:toolswap:toolswap,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91277_(Minecraft.java:1718) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91279_(Minecraft.java:1976) ~[client-1.19.3-20221207.122022-srg.jar%23254!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:xaeroworldmap:xaero_wm_minecraft_runtick,pl:mixin:APP:bookshelf.common.mixins.json:client.AccessorMinecraft,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:carryon.mixins.json:MinecraftMixin,pl:mixin:APP:konkrete.mixin.json:MixinMinecraft,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:playerrevive.mixins.json:MinecraftAccessor,pl:mixin:A,pl:runtimedistcleaner:A}
```

Here's the complete error log: https://mclo.gs/uFbogas (also attached as .txt)

[crash-2023-04-11_11.21.47-client.txt](https://github.com/Parker8283/BowInfinityFix/files/11199076/crash-2023-04-11_11.21.47-client.txt)

Regards

**Comment by Parker8283** [comment]
You're using an out-of-date version of the mod. Update to 2.5.1.

**Comment by jdominguezs** [comment]
> You're using an out-of-date version of the mod. Update to 2.5.1.

You are totally right,

![image](https://user-images.githubusercontent.com/109268957/231161407-bf883d31-b3d1-41ad-88b8-c4ffce6672ac.png)

I just saw the 1.19.4 and ignore it.  My bad, sorry.

Updated to v2.5.1 and working. Thanks!
